# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: WinBooster.Cross_Cleaner_GUI
PackageVersion: 2.0.4.1
InstallerLocale: en-US
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{63C69122-AC80-4866-B328-5C3188A01F76}_is1'
ReleaseDate: 2026-09-16
AppsAndFeaturesEntries:
- ProductCode: '{63C69122-AC80-4866-B328-5C3188A01F76}_is1'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/WinBooster/Cross-Cleaner/releases/download/v2.0.4.1/Cross_Cleaner_Setup.exe
  InstallerSha256: 9b8a2ddef0b729c2627d1fe859a64c74f390bc3103377b565d8c7994eecb6d8b
  InstallerSwitches:
    Custom: /CURRENTUSER
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
    - PackageIdentifier: Microsoft.VCRedist.2015+.x86
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/WinBooster/Cross-Cleaner/releases/download/v2.0.4.1/Cross_Cleaner_Setup.exe
  InstallerSha256: 9b8a2ddef0b729c2627d1fe859a64c74f390bc3103377b565d8c7994eecb6d8b
  InstallerSwitches:
    Custom: /ALLUSERS
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
    - PackageIdentifier: Microsoft.VCRedist.2015+.x86
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\Cross Cleaner'
ManifestType: installer
ManifestVersion: 1.12.0
